name: clickhouse
services:
  server:
    image: clickhouse
    ports:
      - 8123:8123
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
    networks:
      - kafka_default

volumes:
  clickhouse_data:
  clickhouse_logs:

networks:
  kafka_default:
    external: true
# gui interface http://localhost:8123/play
